server:
  port: 13667
spring:
  application:
    name: gateway-server

zuul:
  routes:
  #   yy-service: /yy-server/**   # 路由id，随意写
    yy-service:
        path: /yy-server/**    #映射路径
         url: http://127.0.0.1:2002  # 映射路径对应的实际url地址

eureka:
  client:
    registry-fetch-interval-seconds: 5   #获得服务列表的周期  5s
    service-url:
      # defaultZone: http://166.166.0.199:1998/eureka
        defaultZone: http://127.0.0.1:12345/eureka